services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    environment:
      VIRTUAL_HOST: portainer.${BASE_DOMAIN}
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: portainer.${BASE_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:?}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
volumes:
  portainer_data:
