---
- name: Set docker_version fact
  ansible.builtin.set_fact:
    docker_version: "{{ base_docker_versions[ansible_distribution | lower] }}"

- name: Install acl, net-tools, jq
  ansible.builtin.apt:
    name:
      - acl
      - net-tools
      - jq
    state: present
    update_cache: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: |
      deb [arch=amd64]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release | lower }} stable
    state: present

- name: Install Docker ce
  ansible.builtin.apt:
    name:
      - "docker-ce={{ docker_version }}"
      - "docker-ce-cli={{ docker_version }}"
      - containerd.io
    state: present
    update_cache: true

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: >-
      https://github.com/docker/compose/releases/download/{{ base_docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 'u+x'
