FROM node:18-alpine
WORKDIR /app
RUN apk add --no-cache curl bash
ARG REACT_APP_TEST_VAR
ENV REACT_APP_TEST_VAR=${REACT_APP_TEST_VAR}
RUN ["/bin/sh", "-c", ": ${REACT_APP_TEST_VAR:?REACT_APP_TEST_VAR must be set}"]
COPY package*.json ./
EXPOSE 3000
CMD ["npm", "start"]
